[2023-09-04 18:39:07,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T18:39:06.056923+00:00 [queued]>
[2023-09-04 18:39:07,299] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T18:39:06.056923+00:00 [queued]>
[2023-09-04 18:39:07,300] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-04 18:39:07,301] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-09-04 18:39:07,303] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-04 18:39:07,333] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): A_get_users> on 2023-09-04 18:39:06.056923+00:00
[2023-09-04 18:39:07,344] {standard_task_runner.py:52} INFO - Started process 4065 to run task
[2023-09-04 18:39:07,353] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag_id', 'A_get_users', 'manual__2023-09-04T18:39:06.056923+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpt5jtkrd_', '--error-file', '/tmp/tmpcv2iakqf']
[2023-09-04 18:39:07,356] {standard_task_runner.py:80} INFO - Job 11: Subtask A_get_users
[2023-09-04 18:39:07,517] {task_command.py:369} INFO - Running <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T18:39:06.056923+00:00 [running]> on host 7423ecc7bbb9
[2023-09-04 18:39:07,644] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=my_dag_id
AIRFLOW_CTX_TASK_ID=A_get_users
AIRFLOW_CTX_EXECUTION_DATE=2023-09-04T18:39:06.056923+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-04T18:39:06.056923+00:00
[2023-09-04 18:39:07,646] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-09-04 18:39:07,648] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/scripts/run_r.sh /opt/***/scripts/A_task.R ']
[2023-09-04 18:39:07,662] {subprocess.py:85} INFO - Output:
[2023-09-04 18:39:07,664] {subprocess.py:92} INFO - bash: line 1: /opt/***/scripts/run_r.sh: No such file or directory
[2023-09-04 18:39:07,666] {subprocess.py:96} INFO - Command exited with return code 127
[2023-09-04 18:39:07,689] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-09-04 18:39:07,695] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag_id, task_id=A_get_users, execution_date=20230904T183906, start_date=20230904T183907, end_date=20230904T183907
[2023-09-04 18:39:07,715] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task A_get_users (Bash command failed. The command returned a non-zero exit code 127.; 4065)
[2023-09-04 18:39:07,731] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-04 18:39:07,794] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
