[2023-09-04 22:01:51,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T22:01:49.649878+00:00 [queued]>
[2023-09-04 22:01:51,270] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T22:01:49.649878+00:00 [queued]>
[2023-09-04 22:01:51,277] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-04 22:01:51,278] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-09-04 22:01:51,283] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-04 22:01:51,309] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): A_get_users> on 2023-09-04 22:01:49.649878+00:00
[2023-09-04 22:01:51,320] {standard_task_runner.py:52} INFO - Started process 144 to run task
[2023-09-04 22:01:51,326] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag_id', 'A_get_users', 'manual__2023-09-04T22:01:49.649878+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpwtd83m6g', '--error-file', '/tmp/tmpbgti2cfp']
[2023-09-04 22:01:51,328] {standard_task_runner.py:80} INFO - Job 235: Subtask A_get_users
[2023-09-04 22:01:51,442] {task_command.py:369} INFO - Running <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T22:01:49.649878+00:00 [running]> on host 6f56bd00cbd4
[2023-09-04 22:01:51,654] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=my_dag_id
AIRFLOW_CTX_TASK_ID=A_get_users
AIRFLOW_CTX_EXECUTION_DATE=2023-09-04T22:01:49.649878+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-04T22:01:49.649878+00:00
[2023-09-04 22:01:51,658] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-09-04 22:01:51,664] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/scripts/run_r.sh /opt/***/scripts/A_task.R ']
[2023-09-04 22:01:51,691] {subprocess.py:85} INFO - Output:
[2023-09-04 22:01:52,008] {subprocess.py:92} INFO - Error in library(httr) : there is no package called ‘httr’
[2023-09-04 22:01:52,010] {subprocess.py:92} INFO - Calls: source -> withVisible -> eval -> eval -> library
[2023-09-04 22:01:52,012] {subprocess.py:92} INFO - Execution halted
[2023-09-04 22:01:52,024] {subprocess.py:96} INFO - Command exited with return code 1
[2023-09-04 22:01:52,061] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-04 22:01:52,075] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag_id, task_id=A_get_users, execution_date=20230904T220149, start_date=20230904T220151, end_date=20230904T220152
[2023-09-04 22:01:52,108] {standard_task_runner.py:97} ERROR - Failed to execute job 235 for task A_get_users (Bash command failed. The command returned a non-zero exit code 1.; 144)
[2023-09-04 22:01:52,160] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-04 22:01:52,233] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
