[2023-09-04 18:46:02,208] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T18:46:00.836439+00:00 [queued]>
[2023-09-04 18:46:02,224] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T18:46:00.836439+00:00 [queued]>
[2023-09-04 18:46:02,226] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-09-04 18:46:02,227] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-09-04 18:46:02,228] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-09-04 18:46:02,249] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): A_get_users> on 2023-09-04 18:46:00.836439+00:00
[2023-09-04 18:46:02,259] {standard_task_runner.py:52} INFO - Started process 4413 to run task
[2023-09-04 18:46:02,264] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag_id', 'A_get_users', 'manual__2023-09-04T18:46:00.836439+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp4fcz0jlz', '--error-file', '/tmp/tmp_vedst3v']
[2023-09-04 18:46:02,266] {standard_task_runner.py:80} INFO - Job 12: Subtask A_get_users
[2023-09-04 18:46:02,380] {task_command.py:369} INFO - Running <TaskInstance: my_dag_id.A_get_users manual__2023-09-04T18:46:00.836439+00:00 [running]> on host 7423ecc7bbb9
[2023-09-04 18:46:02,490] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=my_dag_id
AIRFLOW_CTX_TASK_ID=A_get_users
AIRFLOW_CTX_EXECUTION_DATE=2023-09-04T18:46:00.836439+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-09-04T18:46:00.836439+00:00
[2023-09-04 18:46:02,492] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-09-04 18:46:02,495] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/opt/***/dags/scripts/run_r.sh /opt/***/dags/scripts/A_task.R ']
[2023-09-04 18:46:02,509] {subprocess.py:85} INFO - Output:
[2023-09-04 18:46:02,517] {subprocess.py:92} INFO - bash: /opt/***/dags/scripts/run_r.sh: /usr/bin/env: bad interpreter: Permission denied
[2023-09-04 18:46:02,519] {subprocess.py:96} INFO - Command exited with return code 126
[2023-09-04 18:46:02,543] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2023-09-04 18:46:02,549] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag_id, task_id=A_get_users, execution_date=20230904T184600, start_date=20230904T184602, end_date=20230904T184602
[2023-09-04 18:46:02,569] {standard_task_runner.py:97} ERROR - Failed to execute job 12 for task A_get_users (Bash command failed. The command returned a non-zero exit code 126.; 4413)
[2023-09-04 18:46:02,601] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-09-04 18:46:02,661] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
